# -*- coding: utf-8 -*-
"""Hello World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxNaKP4tTfhWJXiI9LvwolZONc3qcsVQ
"""

# This is my first Python code on GitHub

print('Hello World!')